name: Mintlify Multirepo Action

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  multirepo-action:
    runs-on: ubuntu-latest
    name: Run mintlify multirepo action
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Run mintlify github action
        uses: mintlify/multirepo-action@v0.15
        with:
          token: ${{ secrets.DOCS_PARENT_PUSH_TOKEN }}
          target-branch: main
          repos: |
            - owner: mintlify-onboarding
              repo: skip-rest-api
              ref: main
            - owner: mintlify-onboarding
              repo: skip-block-sdk
              ref: main
            - owner: mintlify-onboarding
              repo: skip-slinky
              ref: main
